// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251110223028_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("EntrenadorSequence");

            modelBuilder.HasSequence("MiembroSequence");

            modelBuilder.Entity("Domain.Entities.Actividad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Actividad", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Clase de ritmo y cardio",
                            Nombre = "Zumba"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Entrenamiento funcional de alta intensidad",
                            Nombre = "CrossFit"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Relajación y flexibilidad",
                            Nombre = "Yoga"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Ejercicio cardiovascular en bicicleta",
                            Nombre = "Spinning"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Asistencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClaseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("MiembroId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClaseId");

                    b.HasIndex("MiembroId");

                    b.ToTable("Asistencia", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClaseId = 1,
                            Fecha = new DateTime(2025, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 1
                        },
                        new
                        {
                            Id = 2,
                            ClaseId = 2,
                            Fecha = new DateTime(2025, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 2
                        },
                        new
                        {
                            Id = 3,
                            ClaseId = 3,
                            Fecha = new DateTime(2025, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 3
                        },
                        new
                        {
                            Id = 4,
                            ClaseId = 4,
                            Fecha = new DateTime(2025, 2, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 4
                        },
                        new
                        {
                            Id = 5,
                            ClaseId = 5,
                            Fecha = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 5
                        },
                        new
                        {
                            Id = 6,
                            ClaseId = 6,
                            Fecha = new DateTime(2025, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 6
                        },
                        new
                        {
                            Id = 7,
                            ClaseId = 1,
                            Fecha = new DateTime(2025, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 7
                        },
                        new
                        {
                            Id = 8,
                            ClaseId = 2,
                            Fecha = new DateTime(2025, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 8
                        },
                        new
                        {
                            Id = 9,
                            ClaseId = 3,
                            Fecha = new DateTime(2025, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 9
                        },
                        new
                        {
                            Id = 10,
                            ClaseId = 4,
                            Fecha = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 10
                        },
                        new
                        {
                            Id = 11,
                            ClaseId = 5,
                            Fecha = new DateTime(2025, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 11
                        },
                        new
                        {
                            Id = 12,
                            ClaseId = 6,
                            Fecha = new DateTime(2025, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 12
                        },
                        new
                        {
                            Id = 13,
                            ClaseId = 1,
                            Fecha = new DateTime(2025, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 13
                        },
                        new
                        {
                            Id = 14,
                            ClaseId = 2,
                            Fecha = new DateTime(2025, 2, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 14
                        },
                        new
                        {
                            Id = 15,
                            ClaseId = 3,
                            Fecha = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 15
                        },
                        new
                        {
                            Id = 16,
                            ClaseId = 4,
                            Fecha = new DateTime(2025, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 16
                        },
                        new
                        {
                            Id = 17,
                            ClaseId = 5,
                            Fecha = new DateTime(2025, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 17
                        },
                        new
                        {
                            Id = 18,
                            ClaseId = 6,
                            Fecha = new DateTime(2025, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 18
                        },
                        new
                        {
                            Id = 19,
                            ClaseId = 1,
                            Fecha = new DateTime(2025, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 19
                        },
                        new
                        {
                            Id = 20,
                            ClaseId = 2,
                            Fecha = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 20
                        },
                        new
                        {
                            Id = 21,
                            ClaseId = 3,
                            Fecha = new DateTime(2025, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 21
                        },
                        new
                        {
                            Id = 22,
                            ClaseId = 4,
                            Fecha = new DateTime(2025, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 22
                        },
                        new
                        {
                            Id = 23,
                            ClaseId = 5,
                            Fecha = new DateTime(2025, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 23
                        },
                        new
                        {
                            Id = 24,
                            ClaseId = 6,
                            Fecha = new DateTime(2025, 2, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 24
                        },
                        new
                        {
                            Id = 25,
                            ClaseId = 1,
                            Fecha = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 25
                        });
                });

            modelBuilder.Entity("Domain.Entities.Clase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActividadId")
                        .HasColumnType("int");

                    b.Property<int>("Cupo")
                        .HasColumnType("int");

                    b.Property<int>("Dia")
                        .HasColumnType("int");

                    b.Property<int>("EntrenadorId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ActividadId");

                    b.HasIndex("EntrenadorId");

                    b.ToTable("Clase", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActividadId = 1,
                            Cupo = 20,
                            Dia = 1,
                            EntrenadorId = 2,
                            HoraFin = new TimeSpan(0, 19, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 18, 0, 0, 0),
                            Nombre = "Zumba Inicial"
                        },
                        new
                        {
                            Id = 2,
                            ActividadId = 2,
                            Cupo = 15,
                            Dia = 2,
                            EntrenadorId = 1,
                            HoraFin = new TimeSpan(0, 20, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 19, 0, 0, 0),
                            Nombre = "CrossFit Intermedio"
                        },
                        new
                        {
                            Id = 3,
                            ActividadId = 3,
                            Cupo = 10,
                            Dia = 3,
                            EntrenadorId = 3,
                            HoraFin = new TimeSpan(0, 18, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 17, 0, 0, 0),
                            Nombre = "Yoga Avanzado"
                        },
                        new
                        {
                            Id = 4,
                            ActividadId = 4,
                            Cupo = 12,
                            Dia = 4,
                            EntrenadorId = 5,
                            HoraFin = new TimeSpan(0, 19, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 18, 0, 0, 0),
                            Nombre = "Spinning Cardio"
                        },
                        new
                        {
                            Id = 5,
                            ActividadId = 2,
                            Cupo = 18,
                            Dia = 5,
                            EntrenadorId = 4,
                            HoraFin = new TimeSpan(0, 20, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 19, 0, 0, 0),
                            Nombre = "Funcional Full"
                        },
                        new
                        {
                            Id = 6,
                            ActividadId = 3,
                            Cupo = 8,
                            Dia = 6,
                            EntrenadorId = 3,
                            HoraFin = new TimeSpan(0, 11, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 10, 0, 0, 0),
                            Nombre = "Yoga Relax"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Descuento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Porcentaje")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Descuento", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Estudiante",
                            Porcentaje = 0.10m
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Jubilado",
                            Porcentaje = 0.15m
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Grupo Familiar",
                            Porcentaje = 0.20m
                        });
                });

            modelBuilder.Entity("Domain.Entities.Entrenador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR [EntrenadorSequence]");

                    SqlServerPropertyBuilderExtensions.UseSequence(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Dni")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Telefono")
                        .HasColumnType("int");

                    b.Property<string>("UrlCertificado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlFoto")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Dni")
                        .IsUnique();

                    b.ToTable("Entrenador", (string)null);

                    b.UseTpcMappingStrategy();

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "Pérez",
                            Dni = 42151500,
                            Nombre = "Pablo",
                            UrlFoto = "https://randomuser.me/api/portraits/men/30.jpg"
                        },
                        new
                        {
                            Id = 2,
                            Apellido = "Fernandez",
                            Dni = 29525462,
                            Nombre = "María",
                            UrlFoto = "https://randomuser.me/api/portraits/women/30.jpg"
                        },
                        new
                        {
                            Id = 3,
                            Apellido = "García",
                            Dni = 38252551,
                            Nombre = "Lucas",
                            UrlFoto = "https://randomuser.me/api/portraits/men/31.jpg"
                        },
                        new
                        {
                            Id = 4,
                            Apellido = "González",
                            Dni = 38962541,
                            Nombre = "Carla",
                            UrlFoto = "https://randomuser.me/api/portraits/women/31.jpg"
                        },
                        new
                        {
                            Id = 5,
                            Apellido = "Martínez",
                            Dni = 40001555,
                            Nombre = "Diego",
                            UrlFoto = "https://randomuser.me/api/portraits/men/32.jpg"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Inscripcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClaseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaInscripcion")
                        .HasColumnType("datetime2");

                    b.Property<int>("MiembroId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClaseId");

                    b.HasIndex("MiembroId");

                    b.ToTable("Inscripcion", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClaseId = 1,
                            FechaInscripcion = new DateTime(2025, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 1
                        },
                        new
                        {
                            Id = 2,
                            ClaseId = 2,
                            FechaInscripcion = new DateTime(2025, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 2
                        },
                        new
                        {
                            Id = 3,
                            ClaseId = 3,
                            FechaInscripcion = new DateTime(2025, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 3
                        },
                        new
                        {
                            Id = 4,
                            ClaseId = 4,
                            FechaInscripcion = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 4
                        },
                        new
                        {
                            Id = 5,
                            ClaseId = 5,
                            FechaInscripcion = new DateTime(2025, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 5
                        },
                        new
                        {
                            Id = 6,
                            ClaseId = 6,
                            FechaInscripcion = new DateTime(2025, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 6
                        },
                        new
                        {
                            Id = 7,
                            ClaseId = 1,
                            FechaInscripcion = new DateTime(2025, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 7
                        },
                        new
                        {
                            Id = 8,
                            ClaseId = 2,
                            FechaInscripcion = new DateTime(2025, 2, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 8
                        },
                        new
                        {
                            Id = 9,
                            ClaseId = 3,
                            FechaInscripcion = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 9
                        },
                        new
                        {
                            Id = 10,
                            ClaseId = 4,
                            FechaInscripcion = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 10
                        },
                        new
                        {
                            Id = 11,
                            ClaseId = 5,
                            FechaInscripcion = new DateTime(2025, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 11
                        },
                        new
                        {
                            Id = 12,
                            ClaseId = 6,
                            FechaInscripcion = new DateTime(2025, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 12
                        },
                        new
                        {
                            Id = 13,
                            ClaseId = 1,
                            FechaInscripcion = new DateTime(2025, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 13
                        },
                        new
                        {
                            Id = 14,
                            ClaseId = 2,
                            FechaInscripcion = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 14
                        },
                        new
                        {
                            Id = 15,
                            ClaseId = 3,
                            FechaInscripcion = new DateTime(2025, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 15
                        },
                        new
                        {
                            Id = 16,
                            ClaseId = 4,
                            FechaInscripcion = new DateTime(2025, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 16
                        },
                        new
                        {
                            Id = 17,
                            ClaseId = 5,
                            FechaInscripcion = new DateTime(2025, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 17
                        },
                        new
                        {
                            Id = 18,
                            ClaseId = 6,
                            FechaInscripcion = new DateTime(2025, 2, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 18
                        },
                        new
                        {
                            Id = 19,
                            ClaseId = 1,
                            FechaInscripcion = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 19
                        },
                        new
                        {
                            Id = 20,
                            ClaseId = 2,
                            FechaInscripcion = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 20
                        },
                        new
                        {
                            Id = 21,
                            ClaseId = 3,
                            FechaInscripcion = new DateTime(2025, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 21
                        },
                        new
                        {
                            Id = 22,
                            ClaseId = 4,
                            FechaInscripcion = new DateTime(2025, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 22
                        },
                        new
                        {
                            Id = 23,
                            ClaseId = 5,
                            FechaInscripcion = new DateTime(2025, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 23
                        },
                        new
                        {
                            Id = 24,
                            ClaseId = 6,
                            FechaInscripcion = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 24
                        },
                        new
                        {
                            Id = 25,
                            ClaseId = 1,
                            FechaInscripcion = new DateTime(2025, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 25
                        });
                });

            modelBuilder.Entity("Domain.Entities.Membresia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CostoFinal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("MiembroId")
                        .HasColumnType("int");

                    b.Property<int>("TipoMembresiaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MiembroId")
                        .IsUnique();

                    b.HasIndex("TipoMembresiaId");

                    b.ToTable("Membresia", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CostoFinal = 15000m,
                            FechaInicio = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaVencimiento = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 1,
                            TipoMembresiaId = 1
                        },
                        new
                        {
                            Id = 2,
                            CostoFinal = 40000m,
                            FechaInicio = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaVencimiento = new DateTime(2025, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 2,
                            TipoMembresiaId = 2
                        },
                        new
                        {
                            Id = 3,
                            CostoFinal = 140000m,
                            FechaInicio = new DateTime(2025, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaVencimiento = new DateTime(2026, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 3,
                            TipoMembresiaId = 3
                        },
                        new
                        {
                            Id = 4,
                            CostoFinal = 15000m,
                            FechaInicio = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaVencimiento = new DateTime(2025, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 4,
                            TipoMembresiaId = 1
                        },
                        new
                        {
                            Id = 5,
                            CostoFinal = 40000m,
                            FechaInicio = new DateTime(2025, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaVencimiento = new DateTime(2025, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 5,
                            TipoMembresiaId = 2
                        },
                        new
                        {
                            Id = 6,
                            CostoFinal = 140000m,
                            FechaInicio = new DateTime(2025, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaVencimiento = new DateTime(2026, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 6,
                            TipoMembresiaId = 3
                        },
                        new
                        {
                            Id = 7,
                            CostoFinal = 15000m,
                            FechaInicio = new DateTime(2025, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaVencimiento = new DateTime(2025, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 7,
                            TipoMembresiaId = 1
                        },
                        new
                        {
                            Id = 8,
                            CostoFinal = 40000m,
                            FechaInicio = new DateTime(2025, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaVencimiento = new DateTime(2025, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 8,
                            TipoMembresiaId = 2
                        },
                        new
                        {
                            Id = 9,
                            CostoFinal = 140000m,
                            FechaInicio = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaVencimiento = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 9,
                            TipoMembresiaId = 3
                        },
                        new
                        {
                            Id = 10,
                            CostoFinal = 15000m,
                            FechaInicio = new DateTime(2025, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaVencimiento = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 10,
                            TipoMembresiaId = 1
                        },
                        new
                        {
                            Id = 11,
                            CostoFinal = 40000m,
                            FechaInicio = new DateTime(2025, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaVencimiento = new DateTime(2025, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 11,
                            TipoMembresiaId = 2
                        },
                        new
                        {
                            Id = 12,
                            CostoFinal = 140000m,
                            FechaInicio = new DateTime(2025, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaVencimiento = new DateTime(2026, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 12,
                            TipoMembresiaId = 3
                        },
                        new
                        {
                            Id = 13,
                            CostoFinal = 15000m,
                            FechaInicio = new DateTime(2025, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaVencimiento = new DateTime(2025, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 13,
                            TipoMembresiaId = 1
                        },
                        new
                        {
                            Id = 14,
                            CostoFinal = 40000m,
                            FechaInicio = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaVencimiento = new DateTime(2025, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 14,
                            TipoMembresiaId = 2
                        },
                        new
                        {
                            Id = 15,
                            CostoFinal = 140000m,
                            FechaInicio = new DateTime(2025, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaVencimiento = new DateTime(2026, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 15,
                            TipoMembresiaId = 3
                        },
                        new
                        {
                            Id = 16,
                            CostoFinal = 15000m,
                            FechaInicio = new DateTime(2025, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaVencimiento = new DateTime(2025, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 16,
                            TipoMembresiaId = 1
                        },
                        new
                        {
                            Id = 17,
                            CostoFinal = 40000m,
                            FechaInicio = new DateTime(2025, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaVencimiento = new DateTime(2025, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 17,
                            TipoMembresiaId = 2
                        },
                        new
                        {
                            Id = 18,
                            CostoFinal = 140000m,
                            FechaInicio = new DateTime(2025, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaVencimiento = new DateTime(2026, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 18,
                            TipoMembresiaId = 3
                        },
                        new
                        {
                            Id = 19,
                            CostoFinal = 15000m,
                            FechaInicio = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaVencimiento = new DateTime(2025, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 19,
                            TipoMembresiaId = 1
                        },
                        new
                        {
                            Id = 20,
                            CostoFinal = 40000m,
                            FechaInicio = new DateTime(2025, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaVencimiento = new DateTime(2025, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 20,
                            TipoMembresiaId = 2
                        },
                        new
                        {
                            Id = 21,
                            CostoFinal = 140000m,
                            FechaInicio = new DateTime(2025, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaVencimiento = new DateTime(2026, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 21,
                            TipoMembresiaId = 3
                        },
                        new
                        {
                            Id = 22,
                            CostoFinal = 15000m,
                            FechaInicio = new DateTime(2025, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaVencimiento = new DateTime(2025, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 22,
                            TipoMembresiaId = 1
                        },
                        new
                        {
                            Id = 23,
                            CostoFinal = 40000m,
                            FechaInicio = new DateTime(2025, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaVencimiento = new DateTime(2025, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 23,
                            TipoMembresiaId = 2
                        },
                        new
                        {
                            Id = 24,
                            CostoFinal = 140000m,
                            FechaInicio = new DateTime(2025, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaVencimiento = new DateTime(2026, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 24,
                            TipoMembresiaId = 3
                        },
                        new
                        {
                            Id = 25,
                            CostoFinal = 15000m,
                            FechaInicio = new DateTime(2025, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaVencimiento = new DateTime(2025, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MiembroId = 25,
                            TipoMembresiaId = 1
                        });
                });

            modelBuilder.Entity("Domain.Entities.Miembro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR [MiembroSequence]");

                    SqlServerPropertyBuilderExtensions.UseSequence(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DescuentoId")
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Dni")
                        .HasColumnType("int");

                    b.Property<int?>("EntrenadorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Telefono")
                        .HasColumnType("int");

                    b.Property<string>("UrlFoto")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DescuentoId");

                    b.HasIndex("Dni")
                        .IsUnique();

                    b.HasIndex("EntrenadorId");

                    b.ToTable("Miembro", (string)null);

                    b.UseTpcMappingStrategy();

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "Gómez",
                            DescuentoId = 1,
                            Direccion = "Calle 101",
                            Dni = 41000001,
                            FechaNacimiento = new DateTime(1991, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Juan",
                            Telefono = 110000001,
                            UrlFoto = "https://randomuser.me/api/portraits/men/0.jpg"
                        },
                        new
                        {
                            Id = 2,
                            Apellido = "Ramírez",
                            DescuentoId = 2,
                            Direccion = "Calle 102",
                            Dni = 41000002,
                            FechaNacimiento = new DateTime(1992, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Lucía",
                            Telefono = 110000002,
                            UrlFoto = "https://randomuser.me/api/portraits/men/1.jpg"
                        },
                        new
                        {
                            Id = 3,
                            Apellido = "Fernández",
                            DescuentoId = 3,
                            Direccion = "Calle 103",
                            Dni = 41000003,
                            FechaNacimiento = new DateTime(1992, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Carlos",
                            Telefono = 110000003,
                            UrlFoto = "https://randomuser.me/api/portraits/men/2.jpg"
                        },
                        new
                        {
                            Id = 4,
                            Apellido = "López",
                            DescuentoId = 1,
                            Direccion = "Calle 104",
                            Dni = 41000004,
                            FechaNacimiento = new DateTime(1993, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Mariana",
                            Telefono = 110000004,
                            UrlFoto = "https://randomuser.me/api/portraits/men/3.jpg"
                        },
                        new
                        {
                            Id = 5,
                            Apellido = "Pérez",
                            DescuentoId = 2,
                            Direccion = "Calle 105",
                            Dni = 41000005,
                            FechaNacimiento = new DateTime(1994, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Diego",
                            Telefono = 110000005,
                            UrlFoto = "https://randomuser.me/api/portraits/men/4.jpg"
                        },
                        new
                        {
                            Id = 6,
                            Apellido = "Martínez",
                            DescuentoId = 3,
                            Direccion = "Calle 106",
                            Dni = 41000006,
                            FechaNacimiento = new DateTime(1995, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Sofía",
                            Telefono = 110000006,
                            UrlFoto = "https://randomuser.me/api/portraits/men/5.jpg"
                        },
                        new
                        {
                            Id = 7,
                            Apellido = "García",
                            DescuentoId = 1,
                            Direccion = "Calle 107",
                            Dni = 41000007,
                            FechaNacimiento = new DateTime(1996, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Martín",
                            Telefono = 110000007,
                            UrlFoto = "https://randomuser.me/api/portraits/men/6.jpg"
                        },
                        new
                        {
                            Id = 8,
                            Apellido = "Sosa",
                            DescuentoId = 2,
                            Direccion = "Calle 108",
                            Dni = 41000008,
                            FechaNacimiento = new DateTime(1997, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Camila",
                            Telefono = 110000008,
                            UrlFoto = "https://randomuser.me/api/portraits/men/7.jpg"
                        },
                        new
                        {
                            Id = 9,
                            Apellido = "Vargas",
                            DescuentoId = 3,
                            Direccion = "Calle 109",
                            Dni = 41000009,
                            FechaNacimiento = new DateTime(1998, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Federico",
                            Telefono = 110000009,
                            UrlFoto = "https://randomuser.me/api/portraits/men/8.jpg"
                        },
                        new
                        {
                            Id = 10,
                            Apellido = "Silva",
                            DescuentoId = 1,
                            Direccion = "Calle 110",
                            Dni = 41000010,
                            FechaNacimiento = new DateTime(1999, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Valentina",
                            Telefono = 110000010,
                            UrlFoto = "https://randomuser.me/api/portraits/men/9.jpg"
                        },
                        new
                        {
                            Id = 11,
                            Apellido = "Rodríguez",
                            DescuentoId = 2,
                            Direccion = "Calle 111",
                            Dni = 41000011,
                            FechaNacimiento = new DateTime(2000, 12, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Gonzalo",
                            Telefono = 110000011,
                            UrlFoto = "https://randomuser.me/api/portraits/men/10.jpg"
                        },
                        new
                        {
                            Id = 12,
                            Apellido = "Torres",
                            DescuentoId = 3,
                            Direccion = "Calle 112",
                            Dni = 41000012,
                            FechaNacimiento = new DateTime(2001, 12, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Carolina",
                            Telefono = 110000012,
                            UrlFoto = "https://randomuser.me/api/portraits/men/11.jpg"
                        },
                        new
                        {
                            Id = 13,
                            Apellido = "Alvarez",
                            DescuentoId = 1,
                            Direccion = "Calle 113",
                            Dni = 41000013,
                            FechaNacimiento = new DateTime(2002, 12, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Andrés",
                            Telefono = 110000013,
                            UrlFoto = "https://randomuser.me/api/portraits/men/12.jpg"
                        },
                        new
                        {
                            Id = 14,
                            Apellido = "Molina",
                            DescuentoId = 2,
                            Direccion = "Calle 114",
                            Dni = 41000014,
                            FechaNacimiento = new DateTime(2003, 12, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Florencia",
                            Telefono = 110000014,
                            UrlFoto = "https://randomuser.me/api/portraits/men/13.jpg"
                        },
                        new
                        {
                            Id = 15,
                            Apellido = "Herrera",
                            DescuentoId = 3,
                            Direccion = "Calle 115",
                            Dni = 41000015,
                            FechaNacimiento = new DateTime(2004, 12, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Pablo",
                            Telefono = 110000015,
                            UrlFoto = "https://randomuser.me/api/portraits/men/14.jpg"
                        },
                        new
                        {
                            Id = 16,
                            Apellido = "Rossi",
                            DescuentoId = 1,
                            Direccion = "Calle 116",
                            Dni = 41000016,
                            FechaNacimiento = new DateTime(2005, 12, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Agustina",
                            Telefono = 110000016,
                            UrlFoto = "https://randomuser.me/api/portraits/men/15.jpg"
                        },
                        new
                        {
                            Id = 17,
                            Apellido = "Domínguez",
                            DescuentoId = 2,
                            Direccion = "Calle 117",
                            Dni = 41000017,
                            FechaNacimiento = new DateTime(2006, 12, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Sebastián",
                            Telefono = 110000017,
                            UrlFoto = "https://randomuser.me/api/portraits/men/16.jpg"
                        },
                        new
                        {
                            Id = 18,
                            Apellido = "Ruiz",
                            DescuentoId = 3,
                            Direccion = "Calle 118",
                            Dni = 41000018,
                            FechaNacimiento = new DateTime(2007, 12, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Ana",
                            Telefono = 110000018,
                            UrlFoto = "https://randomuser.me/api/portraits/men/17.jpg"
                        },
                        new
                        {
                            Id = 19,
                            Apellido = "Ortiz",
                            DescuentoId = 1,
                            Direccion = "Calle 119",
                            Dni = 41000019,
                            FechaNacimiento = new DateTime(2008, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Tomás",
                            Telefono = 110000019,
                            UrlFoto = "https://randomuser.me/api/portraits/men/18.jpg"
                        },
                        new
                        {
                            Id = 20,
                            Apellido = "Iglesias",
                            DescuentoId = 2,
                            Direccion = "Calle 120",
                            Dni = 41000020,
                            FechaNacimiento = new DateTime(2009, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Laura",
                            Telefono = 110000020,
                            UrlFoto = "https://randomuser.me/api/portraits/men/19.jpg"
                        },
                        new
                        {
                            Id = 21,
                            Apellido = "Castro",
                            DescuentoId = 3,
                            Direccion = "Calle 121",
                            Dni = 41000021,
                            FechaNacimiento = new DateTime(2010, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Ricardo",
                            Telefono = 110000021,
                            UrlFoto = "https://randomuser.me/api/portraits/men/20.jpg"
                        },
                        new
                        {
                            Id = 22,
                            Apellido = "Díaz",
                            DescuentoId = 1,
                            Direccion = "Calle 122",
                            Dni = 41000022,
                            FechaNacimiento = new DateTime(2011, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Gabriela",
                            Telefono = 110000022,
                            UrlFoto = "https://randomuser.me/api/portraits/men/21.jpg"
                        },
                        new
                        {
                            Id = 23,
                            Apellido = "Páez",
                            DescuentoId = 2,
                            Direccion = "Calle 123",
                            Dni = 41000023,
                            FechaNacimiento = new DateTime(2012, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Nicolás",
                            Telefono = 110000023,
                            UrlFoto = "https://randomuser.me/api/portraits/men/22.jpg"
                        },
                        new
                        {
                            Id = 24,
                            Apellido = "Suárez",
                            DescuentoId = 3,
                            Direccion = "Calle 124",
                            Dni = 41000024,
                            FechaNacimiento = new DateTime(2013, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Sabrina",
                            Telefono = 110000024,
                            UrlFoto = "https://randomuser.me/api/portraits/men/23.jpg"
                        },
                        new
                        {
                            Id = 25,
                            Apellido = "Méndez",
                            DescuentoId = 1,
                            Direccion = "Calle 125",
                            Dni = 41000025,
                            FechaNacimiento = new DateTime(2014, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Bruno",
                            Telefono = 110000025,
                            UrlFoto = "https://randomuser.me/api/portraits/men/24.jpg"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("MembresiaId")
                        .HasColumnType("int");

                    b.Property<int>("MetodoPago")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MembresiaId");

                    b.ToTable("Pago", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Fecha = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MembresiaId = 1,
                            MetodoPago = 1,
                            Monto = 15000m
                        },
                        new
                        {
                            Id = 2,
                            Fecha = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MembresiaId = 2,
                            MetodoPago = 2,
                            Monto = 40000m
                        },
                        new
                        {
                            Id = 3,
                            Fecha = new DateTime(2025, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MembresiaId = 3,
                            MetodoPago = 3,
                            Monto = 140000m
                        },
                        new
                        {
                            Id = 4,
                            Fecha = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MembresiaId = 4,
                            MetodoPago = 0,
                            Monto = 15000m
                        },
                        new
                        {
                            Id = 5,
                            Fecha = new DateTime(2025, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MembresiaId = 5,
                            MetodoPago = 1,
                            Monto = 40000m
                        },
                        new
                        {
                            Id = 6,
                            Fecha = new DateTime(2025, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MembresiaId = 6,
                            MetodoPago = 2,
                            Monto = 140000m
                        },
                        new
                        {
                            Id = 7,
                            Fecha = new DateTime(2025, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MembresiaId = 7,
                            MetodoPago = 3,
                            Monto = 15000m
                        },
                        new
                        {
                            Id = 8,
                            Fecha = new DateTime(2025, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MembresiaId = 8,
                            MetodoPago = 0,
                            Monto = 40000m
                        },
                        new
                        {
                            Id = 9,
                            Fecha = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MembresiaId = 9,
                            MetodoPago = 1,
                            Monto = 140000m
                        },
                        new
                        {
                            Id = 10,
                            Fecha = new DateTime(2025, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MembresiaId = 10,
                            MetodoPago = 2,
                            Monto = 15000m
                        },
                        new
                        {
                            Id = 11,
                            Fecha = new DateTime(2025, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MembresiaId = 11,
                            MetodoPago = 3,
                            Monto = 40000m
                        },
                        new
                        {
                            Id = 12,
                            Fecha = new DateTime(2025, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MembresiaId = 12,
                            MetodoPago = 0,
                            Monto = 140000m
                        },
                        new
                        {
                            Id = 13,
                            Fecha = new DateTime(2025, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MembresiaId = 13,
                            MetodoPago = 1,
                            Monto = 15000m
                        },
                        new
                        {
                            Id = 14,
                            Fecha = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MembresiaId = 14,
                            MetodoPago = 2,
                            Monto = 40000m
                        },
                        new
                        {
                            Id = 15,
                            Fecha = new DateTime(2025, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MembresiaId = 15,
                            MetodoPago = 3,
                            Monto = 140000m
                        },
                        new
                        {
                            Id = 16,
                            Fecha = new DateTime(2025, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MembresiaId = 16,
                            MetodoPago = 0,
                            Monto = 15000m
                        },
                        new
                        {
                            Id = 17,
                            Fecha = new DateTime(2025, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MembresiaId = 17,
                            MetodoPago = 1,
                            Monto = 40000m
                        },
                        new
                        {
                            Id = 18,
                            Fecha = new DateTime(2025, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MembresiaId = 18,
                            MetodoPago = 2,
                            Monto = 140000m
                        },
                        new
                        {
                            Id = 19,
                            Fecha = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MembresiaId = 19,
                            MetodoPago = 3,
                            Monto = 15000m
                        },
                        new
                        {
                            Id = 20,
                            Fecha = new DateTime(2025, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MembresiaId = 20,
                            MetodoPago = 0,
                            Monto = 40000m
                        },
                        new
                        {
                            Id = 21,
                            Fecha = new DateTime(2025, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MembresiaId = 21,
                            MetodoPago = 1,
                            Monto = 140000m
                        },
                        new
                        {
                            Id = 22,
                            Fecha = new DateTime(2025, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MembresiaId = 22,
                            MetodoPago = 2,
                            Monto = 15000m
                        },
                        new
                        {
                            Id = 23,
                            Fecha = new DateTime(2025, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MembresiaId = 23,
                            MetodoPago = 3,
                            Monto = 40000m
                        },
                        new
                        {
                            Id = 24,
                            Fecha = new DateTime(2025, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MembresiaId = 24,
                            MetodoPago = 0,
                            Monto = 140000m
                        },
                        new
                        {
                            Id = 25,
                            Fecha = new DateTime(2025, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MembresiaId = 25,
                            MetodoPago = 1,
                            Monto = 15000m
                        });
                });

            modelBuilder.Entity("Domain.Entities.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<int>("PagoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PagoId")
                        .IsUnique();

                    b.ToTable("Ticket", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Detalle = "Pago registrado el 2025-01-02 por Juan Gómez. Monto: $15.000. Método: QR.",
                            FechaEmision = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PagoId = 1
                        },
                        new
                        {
                            Id = 2,
                            Detalle = "Pago registrado el 2025-01-03 por Lucía Ramírez. Monto: $40.000. Método: TarjetaDebito.",
                            FechaEmision = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PagoId = 2
                        },
                        new
                        {
                            Id = 3,
                            Detalle = "Pago registrado el 2025-01-04 por Carlos Fernández. Monto: $140.000. Método: TarjetaCredito.",
                            FechaEmision = new DateTime(2025, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PagoId = 3
                        },
                        new
                        {
                            Id = 4,
                            Detalle = "Pago registrado el 2025-01-05 por Mariana López. Monto: $15.000. Método: Efectivo.",
                            FechaEmision = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PagoId = 4
                        },
                        new
                        {
                            Id = 5,
                            Detalle = "Pago registrado el 2025-01-06 por Diego Pérez. Monto: $40.000. Método: QR.",
                            FechaEmision = new DateTime(2025, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PagoId = 5
                        },
                        new
                        {
                            Id = 6,
                            Detalle = "Pago registrado el 2025-01-07 por Sofía Martínez. Monto: $140.000. Método: TarjetaDebito.",
                            FechaEmision = new DateTime(2025, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PagoId = 6
                        },
                        new
                        {
                            Id = 7,
                            Detalle = "Pago registrado el 2025-01-08 por Martín García. Monto: $15.000. Método: TarjetaCredito.",
                            FechaEmision = new DateTime(2025, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PagoId = 7
                        },
                        new
                        {
                            Id = 8,
                            Detalle = "Pago registrado el 2025-01-09 por Camila Sosa. Monto: $40.000. Método: Efectivo.",
                            FechaEmision = new DateTime(2025, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PagoId = 8
                        },
                        new
                        {
                            Id = 9,
                            Detalle = "Pago registrado el 2025-01-10 por Federico Vargas. Monto: $140.000. Método: QR.",
                            FechaEmision = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PagoId = 9
                        },
                        new
                        {
                            Id = 10,
                            Detalle = "Pago registrado el 2025-01-11 por Valentina Silva. Monto: $15.000. Método: TarjetaDebito.",
                            FechaEmision = new DateTime(2025, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PagoId = 10
                        },
                        new
                        {
                            Id = 11,
                            Detalle = "Pago registrado el 2025-01-12 por Gonzalo Rodríguez. Monto: $40.000. Método: TarjetaCredito.",
                            FechaEmision = new DateTime(2025, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PagoId = 11
                        },
                        new
                        {
                            Id = 12,
                            Detalle = "Pago registrado el 2025-01-13 por Carolina Torres. Monto: $140.000. Método: Efectivo.",
                            FechaEmision = new DateTime(2025, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PagoId = 12
                        },
                        new
                        {
                            Id = 13,
                            Detalle = "Pago registrado el 2025-01-14 por Andrés Alvarez. Monto: $15.000. Método: QR.",
                            FechaEmision = new DateTime(2025, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PagoId = 13
                        },
                        new
                        {
                            Id = 14,
                            Detalle = "Pago registrado el 2025-01-15 por Florencia Molina. Monto: $40.000. Método: TarjetaDebito.",
                            FechaEmision = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PagoId = 14
                        },
                        new
                        {
                            Id = 15,
                            Detalle = "Pago registrado el 2025-01-16 por Pablo Herrera. Monto: $140.000. Método: TarjetaCredito.",
                            FechaEmision = new DateTime(2025, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PagoId = 15
                        },
                        new
                        {
                            Id = 16,
                            Detalle = "Pago registrado el 2025-01-17 por Agustina Rossi. Monto: $15.000. Método: Efectivo.",
                            FechaEmision = new DateTime(2025, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PagoId = 16
                        },
                        new
                        {
                            Id = 17,
                            Detalle = "Pago registrado el 2025-01-18 por Sebastián Domínguez. Monto: $40.000. Método: QR.",
                            FechaEmision = new DateTime(2025, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PagoId = 17
                        },
                        new
                        {
                            Id = 18,
                            Detalle = "Pago registrado el 2025-01-19 por Ana Ruiz. Monto: $140.000. Método: TarjetaDebito.",
                            FechaEmision = new DateTime(2025, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PagoId = 18
                        },
                        new
                        {
                            Id = 19,
                            Detalle = "Pago registrado el 2025-01-20 por Tomás Ortiz. Monto: $15.000. Método: TarjetaCredito.",
                            FechaEmision = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PagoId = 19
                        },
                        new
                        {
                            Id = 20,
                            Detalle = "Pago registrado el 2025-01-21 por Laura Iglesias. Monto: $40.000. Método: Efectivo.",
                            FechaEmision = new DateTime(2025, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PagoId = 20
                        },
                        new
                        {
                            Id = 21,
                            Detalle = "Pago registrado el 2025-01-22 por Ricardo Castro. Monto: $140.000. Método: QR.",
                            FechaEmision = new DateTime(2025, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PagoId = 21
                        },
                        new
                        {
                            Id = 22,
                            Detalle = "Pago registrado el 2025-01-23 por Gabriela Díaz. Monto: $15.000. Método: TarjetaDebito.",
                            FechaEmision = new DateTime(2025, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PagoId = 22
                        },
                        new
                        {
                            Id = 23,
                            Detalle = "Pago registrado el 2025-01-24 por Nicolás Páez. Monto: $40.000. Método: TarjetaCredito.",
                            FechaEmision = new DateTime(2025, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PagoId = 23
                        },
                        new
                        {
                            Id = 24,
                            Detalle = "Pago registrado el 2025-01-25 por Sabrina Suárez. Monto: $140.000. Método: Efectivo.",
                            FechaEmision = new DateTime(2025, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PagoId = 24
                        },
                        new
                        {
                            Id = 25,
                            Detalle = "Pago registrado el 2025-01-26 por Bruno Méndez. Monto: $15.000. Método: QR.",
                            FechaEmision = new DateTime(2025, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PagoId = 25
                        });
                });

            modelBuilder.Entity("Domain.Entities.TipoMembresia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DuracionDias")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoMembresia", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Costo = 15000m,
                            DuracionDias = 30,
                            Nombre = "Mensual"
                        },
                        new
                        {
                            Id = 2,
                            Costo = 40000m,
                            DuracionDias = 90,
                            Nombre = "Trimestral"
                        },
                        new
                        {
                            Id = 3,
                            Costo = 140000m,
                            DuracionDias = 365,
                            Nombre = "Anual"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Asistencia", b =>
                {
                    b.HasOne("Domain.Entities.Clase", "Clase")
                        .WithMany("Asistencias")
                        .HasForeignKey("ClaseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.Entities.Miembro", "Miembro")
                        .WithMany("Asistencias")
                        .HasForeignKey("MiembroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clase");

                    b.Navigation("Miembro");
                });

            modelBuilder.Entity("Domain.Entities.Clase", b =>
                {
                    b.HasOne("Domain.Entities.Actividad", "Actividad")
                        .WithMany("Clases")
                        .HasForeignKey("ActividadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Entrenador", "Entrenador")
                        .WithMany("Clases")
                        .HasForeignKey("EntrenadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actividad");

                    b.Navigation("Entrenador");
                });

            modelBuilder.Entity("Domain.Entities.Inscripcion", b =>
                {
                    b.HasOne("Domain.Entities.Clase", "Clase")
                        .WithMany("Inscripciones")
                        .HasForeignKey("ClaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Miembro", "Miembro")
                        .WithMany("Inscripciones")
                        .HasForeignKey("MiembroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clase");

                    b.Navigation("Miembro");
                });

            modelBuilder.Entity("Domain.Entities.Membresia", b =>
                {
                    b.HasOne("Domain.Entities.Miembro", "Miembro")
                        .WithOne("Membresia")
                        .HasForeignKey("Domain.Entities.Membresia", "MiembroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.TipoMembresia", "TipoMembresia")
                        .WithMany("Membresias")
                        .HasForeignKey("TipoMembresiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Miembro");

                    b.Navigation("TipoMembresia");
                });

            modelBuilder.Entity("Domain.Entities.Miembro", b =>
                {
                    b.HasOne("Domain.Entities.Descuento", "Descuento")
                        .WithMany("Miembros")
                        .HasForeignKey("DescuentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Entrenador", "Entrenador")
                        .WithMany("Miembros")
                        .HasForeignKey("EntrenadorId");

                    b.Navigation("Descuento");

                    b.Navigation("Entrenador");
                });

            modelBuilder.Entity("Domain.Entities.Pago", b =>
                {
                    b.HasOne("Domain.Entities.Membresia", "Membresia")
                        .WithMany("Pagos")
                        .HasForeignKey("MembresiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Membresia");
                });

            modelBuilder.Entity("Domain.Entities.Ticket", b =>
                {
                    b.HasOne("Domain.Entities.Pago", "Pago")
                        .WithOne("Ticket")
                        .HasForeignKey("Domain.Entities.Ticket", "PagoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pago");
                });

            modelBuilder.Entity("Domain.Entities.Actividad", b =>
                {
                    b.Navigation("Clases");
                });

            modelBuilder.Entity("Domain.Entities.Clase", b =>
                {
                    b.Navigation("Asistencias");

                    b.Navigation("Inscripciones");
                });

            modelBuilder.Entity("Domain.Entities.Descuento", b =>
                {
                    b.Navigation("Miembros");
                });

            modelBuilder.Entity("Domain.Entities.Entrenador", b =>
                {
                    b.Navigation("Clases");

                    b.Navigation("Miembros");
                });

            modelBuilder.Entity("Domain.Entities.Membresia", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("Domain.Entities.Miembro", b =>
                {
                    b.Navigation("Asistencias");

                    b.Navigation("Inscripciones");

                    b.Navigation("Membresia")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Pago", b =>
                {
                    b.Navigation("Ticket")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.TipoMembresia", b =>
                {
                    b.Navigation("Membresias");
                });
#pragma warning restore 612, 618
        }
    }
}
